export const STYLE_START_COMMENT = '/* KAZE STYLE STYLE START */';
export const STYLE_END_COMMENT = '/* KAZE STYLE STYLE END */';

export const GLOBAL_STYLE_START_COMMENT = '/* KAZE STYLE GLOBAL STYLE START */';
export const GLOBAL_STYLE_END_COMMENT = '/* KAZE STYLE GLOBAL STYLE END */';
